id: A0016FA63
title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
  of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:39:40.266825
  last_modified_at: 2022-03-01 03:39:40.266828
