id: A0016FA63
title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
  Practice of the Ḍākinī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:39:40.264743
  last_modified_at: 2022-03-01 03:39:40.264746
